version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mealvote1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 mealvote.wsgi:application
    ports:
      - "8000:8000"


volumes:
  postgres_data:
